version: '3.7'

services:
  db:
    image: postgres:13
    user: root
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    image: odoo-jupyter
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "10010:8888"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoo-network

volumes:
  odoo-db-data:
  odoo-data:

networks:
  odoo-network:
